<?php

namespace Database\Seeders;

use App\Domain\CMS\Models\Destination;
use Illuminate\Database\Seeder;

class DestinationSeeder extends Seeder
{
    public function run(): void
    {
        $destinations = [
            // =============================================
            // WISATA (5 entries)
            // =============================================
            [
                'name' => 'Kayangan Api',
                'description' => 'Api abadi yang menyala alami dari sumber gas bumi di bawah tanah. Merupakan ikon wisata Bojonegoro yang telah ada sejak zaman dahulu dan menjadi simbol Kabupaten Bojonegoro.',
                'address' => 'Desa Sendangharjo, Kecamatan Ngasem, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'wisata',
                'image_url' => '',
                'rating' => 4.3,
                'review_count' => 150,
                'price_range' => 'Rp 5.000 - Rp 10.000',
                'facilities' => ['Parkir', 'Toilet', 'Warung Makan', 'Musholla', 'Area Foto'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.2975,
                'longitude' => 111.8647,
                'is_featured' => true,
            ],
            [
                'name' => 'Waduk Pacal',
                'description' => 'Waduk yang dibangun pada masa kolonial Belanda ini menawarkan pemandangan alam yang asri dengan perbukitan hijau di sekitarnya. Cocok untuk piknik keluarga dan menikmati sunset.',
                'address' => 'Desa Pacal, Kecamatan Dander, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'wisata',
                'image_url' => '',
                'rating' => 4.1,
                'review_count' => 85,
                'price_range' => 'Gratis',
                'facilities' => ['Parkir', 'Warung Makan', 'Area Piknik', 'Spot Foto'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.3361,
                'longitude' => 111.7408,
                'is_featured' => true,
            ],
            [
                'name' => 'Wana Wisata Dander',
                'description' => 'Hutan wisata yang menawarkan suasana alam pegunungan yang sejuk dan asri. Terdapat jalur trekking, area camping, dan pemandangan hutan jati yang rindang.',
                'address' => 'Kecamatan Dander, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'wisata',
                'image_url' => '',
                'rating' => 4.0,
                'review_count' => 62,
                'price_range' => 'Rp 5.000 - Rp 15.000',
                'facilities' => ['Parkir', 'Toilet', 'Area Camping', 'Jalur Trekking', 'Warung'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.3450,
                'longitude' => 111.7500,
                'is_featured' => false,
            ],
            [
                'name' => 'Alun-Alun Bojonegoro',
                'description' => 'Pusat kota Bojonegoro yang telah direnovasi menjadi ruang publik modern. Dilengkapi taman, air mancur, area bermain anak, dan sering digunakan untuk acara rakyat.',
                'address' => 'Jl. Alun-Alun, Kelurahan Kadipaten, Kecamatan Bojonegoro, Kabupaten Bojonegoro',
                'category' => 'wisata',
                'image_url' => '',
                'rating' => 4.2,
                'review_count' => 200,
                'price_range' => 'Gratis',
                'facilities' => ['Parkir', 'Toilet', 'Taman', 'Area Bermain Anak', 'WiFi', 'Pedagang Kaki Lima'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.1503,
                'longitude' => 111.8819,
                'is_featured' => false,
            ],
            [
                'name' => 'Taman Tirta Wisata',
                'description' => 'Taman wisata air yang menyediakan kolam renang, wahana air, dan area rekreasi keluarga. Tempat yang populer untuk liburan akhir pekan bersama keluarga.',
                'address' => 'Kecamatan Bojonegoro, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'wisata',
                'image_url' => '',
                'rating' => 3.9,
                'review_count' => 95,
                'price_range' => 'Rp 10.000 - Rp 25.000',
                'facilities' => ['Parkir', 'Toilet', 'Kolam Renang', 'Wahana Air', 'Kantin', 'Musholla'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.1520,
                'longitude' => 111.8850,
                'is_featured' => false,
            ],

            // =============================================
            // HOTEL (6 entries)
            // =============================================
            [
                'name' => 'Favehotel Sudirman Bojonegoro',
                'description' => 'Hotel bintang 3 modern di pusat kota Bojonegoro dengan kamar yang bersih dan nyaman. Dilengkapi restoran, meeting room, dan akses mudah ke pusat bisnis.',
                'address' => 'Jl. Jenderal Sudirman, Kecamatan Bojonegoro, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'hotel',
                'image_url' => '',
                'rating' => 4.5,
                'review_count' => 120,
                'price_range' => 'Rp 615.000+',
                'facilities' => ['WiFi', 'AC', 'Restoran', 'Parkir', 'Meeting Room', 'Resepsionis 24 Jam', 'Laundry'],
                'phone' => '0353-331888',
                'website' => 'https://www.favehotels.com',
                'latitude' => -7.1498,
                'longitude' => 111.8830,
                'is_featured' => true,
            ],
            [
                'name' => 'Hotel Bonero Bojonegoro',
                'description' => 'Hotel strategis di Bojonegoro yang menawarkan akomodasi nyaman dengan harga terjangkau. Cocok untuk perjalanan bisnis maupun wisata.',
                'address' => 'Jl. Ahmad Yani, Kecamatan Bojonegoro, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'hotel',
                'image_url' => '',
                'rating' => 4.0,
                'review_count' => 78,
                'price_range' => 'Rp 133.000+',
                'facilities' => ['WiFi', 'AC', 'Parkir', 'Resepsionis 24 Jam', 'TV'],
                'phone' => '0353-881199',
                'website' => null,
                'latitude' => -7.1505,
                'longitude' => 111.8815,
                'is_featured' => true,
            ],
            [
                'name' => 'OYO 2671 Wisma Djaja Syariah',
                'description' => 'Penginapan syariah yang bersih dan nyaman dengan harga ekonomis. Lokasi strategis di pusat kota Bojonegoro.',
                'address' => 'Kecamatan Bojonegoro, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'hotel',
                'image_url' => '',
                'rating' => 3.4,
                'review_count' => 45,
                'price_range' => 'Rp 200.000+',
                'facilities' => ['WiFi', 'AC', 'Parkir', 'Musholla', 'Resepsionis 24 Jam'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.1510,
                'longitude' => 111.8825,
                'is_featured' => false,
            ],
            [
                'name' => 'Nirwana Hotel',
                'description' => 'Hotel dengan suasana tenang dan nyaman di Bojonegoro. Menyediakan kamar bersih dengan fasilitas dasar yang memadai untuk bisnis dan wisata.',
                'address' => 'Kecamatan Bojonegoro, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'hotel',
                'image_url' => '',
                'rating' => 3.5,
                'review_count' => 30,
                'price_range' => 'Rp 192.000+',
                'facilities' => ['WiFi', 'AC', 'Parkir', 'TV', 'Resepsionis 24 Jam'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.1515,
                'longitude' => 111.8840,
                'is_featured' => false,
            ],
            [
                'name' => 'MCM Hotel Wisata',
                'description' => 'Hotel wisata di Bojonegoro yang menawarkan pengalaman menginap nyaman dengan fasilitas lengkap termasuk restoran dan area parkir luas.',
                'address' => 'Kecamatan Bojonegoro, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'hotel',
                'image_url' => '',
                'rating' => 3.6,
                'review_count' => 42,
                'price_range' => 'Rp 164.000+',
                'facilities' => ['WiFi', 'AC', 'Parkir', 'Restoran', 'Resepsionis 24 Jam'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.1490,
                'longitude' => 111.8810,
                'is_featured' => false,
            ],
            [
                'name' => 'Hotel Wisma Djaja Syariah',
                'description' => 'Penginapan berbasis syariah di pusat kota Bojonegoro. Menyediakan kamar bersih, Musholla, dan suasana Islami yang nyaman.',
                'address' => 'Kecamatan Bojonegoro, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'hotel',
                'image_url' => '',
                'rating' => 3.3,
                'review_count' => 38,
                'price_range' => 'Rp 206.000+',
                'facilities' => ['WiFi', 'AC', 'Parkir', 'Musholla', 'Resepsionis 24 Jam'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.1508,
                'longitude' => 111.8822,
                'is_featured' => false,
            ],

            // =============================================
            // KULINER (27 entries)
            // =============================================
            [
                'name' => "D'Pojok Kampung Restoran",
                'description' => 'Restoran dengan suasana kampung yang asri, menyajikan masakan Cina dan Asia. Terkenal dengan makan malam yang mantap dan suasana makan bersama yang nyaman.',
                'address' => 'Kecamatan Bojonegoro, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'kuliner',
                'image_url' => '',
                'rating' => 5.0,
                'review_count' => 3,
                'price_range' => '$',
                'facilities' => ['Parkir', 'WiFi', 'AC'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.1495,
                'longitude' => 111.8828,
                'is_featured' => true,
            ],
            [
                'name' => 'Adelia Cafe & Resto',
                'description' => 'Kafe dan restoran populer di Bojonegoro dengan menu Cina dan Internasional. Suasana nyaman dan cozy, cocok untuk makan bersama keluarga atau teman.',
                'address' => 'Kecamatan Bojonegoro, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'kuliner',
                'image_url' => '',
                'rating' => 4.2,
                'review_count' => 25,
                'price_range' => '$$-$$$',
                'facilities' => ['Parkir', 'WiFi', 'AC', 'Live Music'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.1502,
                'longitude' => 111.8835,
                'is_featured' => true,
            ],
            [
                'name' => 'Javanilla Resto & Bakery',
                'description' => 'Resto keluarga yang dikenal dengan salad luar biasa dan aneka menu bakery. Suasana hangat cocok untuk makan bersama keluarga.',
                'address' => 'Kecamatan Bojonegoro, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'kuliner',
                'image_url' => '',
                'rating' => 4.0,
                'review_count' => 7,
                'price_range' => '$$-$$$',
                'facilities' => ['Parkir', 'WiFi', 'AC'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.1500,
                'longitude' => 111.8820,
                'is_featured' => false,
            ],
            [
                'name' => 'Warung Apung Rahmawati',
                'description' => 'Warung terapung unik yang menyajikan makanan laut dan masakan Asia. Ayam bakarnya juara dengan suasana makan yang berbeda di atas air.',
                'address' => 'Kecamatan Bojonegoro, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'kuliner',
                'image_url' => '',
                'rating' => 3.8,
                'review_count' => 22,
                'price_range' => '$$-$$$',
                'facilities' => ['Parkir', 'Musholla', 'Area Terbuka'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.1530,
                'longitude' => 111.8800,
                'is_featured' => false,
            ],
            [
                'name' => 'Gudeg Lumintu Bu Anna',
                'description' => 'Warung gudeg khas Jawa dengan cita rasa autentik. Menyajikan gudeg dengan sambal krecek dan lauk pauk tradisional.',
                'address' => 'Kecamatan Bojonegoro, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'kuliner',
                'image_url' => '',
                'rating' => 0,
                'review_count' => 0,
                'price_range' => '$',
                'facilities' => ['Parkir'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.1485,
                'longitude' => 111.8845,
                'is_featured' => false,
            ],
            [
                'name' => 'Pondok Tempe Penyet Bu Trisno',
                'description' => 'Warung legendaris yang terkenal dengan tempe penyet dan sambalnya yang enak. Harga murah dengan rasa yang tak kalah dari restoran mewah.',
                'address' => 'Kecamatan Bojonegoro, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'kuliner',
                'image_url' => '',
                'rating' => 4.0,
                'review_count' => 7,
                'price_range' => '$',
                'facilities' => ['Parkir'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.1488,
                'longitude' => 111.8832,
                'is_featured' => false,
            ],
            [
                'name' => 'The Pits Kitchen',
                'description' => 'Cafe asyik dengan suasana modern dan menu Indonesia yang lezat. Tempat nongkrong favorit anak muda Bojonegoro.',
                'address' => 'Kecamatan Bojonegoro, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'kuliner',
                'image_url' => '',
                'rating' => 5.0,
                'review_count' => 1,
                'price_range' => '$$-$$$',
                'facilities' => ['Parkir', 'WiFi', 'AC'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.1492,
                'longitude' => 111.8838,
                'is_featured' => false,
            ],
            [
                'name' => 'Dumi',
                'description' => 'Restoran Indonesia yang terkenal dengan nasi flambe dan bebek gempur. Menu unik dengan penyajian yang menarik.',
                'address' => 'Kecamatan Bojonegoro, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'kuliner',
                'image_url' => '',
                'rating' => 5.0,
                'review_count' => 1,
                'price_range' => '$$-$$$',
                'facilities' => ['Parkir', 'WiFi', 'AC'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.1497,
                'longitude' => 111.8842,
                'is_featured' => false,
            ],
            [
                'name' => 'Resto Griya MCM',
                'description' => 'Restoran di kompleks hotel MCM yang menyajikan masakan Indonesia. Suasana nyaman untuk makan bersama keluarga.',
                'address' => 'Kecamatan Bojonegoro, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'kuliner',
                'image_url' => '',
                'rating' => 0,
                'review_count' => 0,
                'price_range' => '$',
                'facilities' => ['Parkir', 'AC', 'WiFi'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.1491,
                'longitude' => 111.8812,
                'is_featured' => false,
            ],
            [
                'name' => 'Bebek Pari Sambel Ijo',
                'description' => 'Warung spesialis bebek dengan sambal ijo khas. Bebek digoreng kering dengan bumbu yang meresap sempurna.',
                'address' => 'Kecamatan Bojonegoro, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'kuliner',
                'image_url' => '',
                'rating' => 0,
                'review_count' => 0,
                'price_range' => '$',
                'facilities' => ['Parkir'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.1518,
                'longitude' => 111.8805,
                'is_featured' => false,
            ],
            [
                'name' => 'Kinan Pizza Mama',
                'description' => 'Restoran pizza lokal dengan cita rasa Italia yang disesuaikan dengan lidah Indonesia. Harga terjangkau untuk pizza berkualitas.',
                'address' => 'Kecamatan Bojonegoro, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'kuliner',
                'image_url' => '',
                'rating' => 0,
                'review_count' => 0,
                'price_range' => '$',
                'facilities' => ['Parkir', 'WiFi'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.1505,
                'longitude' => 111.8848,
                'is_featured' => false,
            ],
            [
                'name' => 'Chinese Food Tunggal',
                'description' => 'Restoran masakan Cina premium di Bojonegoro. Menyajikan hidangan otentik dengan bahan-bahan berkualitas tinggi.',
                'address' => 'Kecamatan Bojonegoro, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'kuliner',
                'image_url' => '',
                'rating' => 0,
                'review_count' => 0,
                'price_range' => '$$$$',
                'facilities' => ['Parkir', 'AC', 'WiFi'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.1500,
                'longitude' => 111.8815,
                'is_featured' => false,
            ],
            [
                'name' => 'Wisata Kuliner Dhong Gedang',
                'description' => 'Pusat kuliner yang menyajikan berbagai masakan Indonesia tradisional. Suasana wisata kuliner yang unik khas Bojonegoro.',
                'address' => 'Kecamatan Bojonegoro, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'kuliner',
                'image_url' => '',
                'rating' => 0,
                'review_count' => 0,
                'price_range' => '$',
                'facilities' => ['Parkir', 'Area Terbuka'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.1525,
                'longitude' => 111.8808,
                'is_featured' => false,
            ],
            [
                'name' => 'Pawon Seafood dan Resto',
                'description' => 'Restoran seafood populer dengan menu lengkap dan harga terjangkau. Menyajikan berbagai pilihan makanan laut segar dan masakan Asia.',
                'address' => 'Kecamatan Bojonegoro, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'kuliner',
                'image_url' => '',
                'rating' => 3.8,
                'review_count' => 13,
                'price_range' => '$$-$$$',
                'facilities' => ['Parkir', 'AC', 'WiFi', 'Area VIP'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.1512,
                'longitude' => 111.8818,
                'is_featured' => false,
            ],
            [
                'name' => 'Gusima Seafood Resto',
                'description' => 'Restoran seafood yang menyajikan hidangan laut segar dengan bumbu khas Indonesia. Suasana nyaman untuk makan bersama.',
                'address' => 'Kecamatan Bojonegoro, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'kuliner',
                'image_url' => '',
                'rating' => 0,
                'review_count' => 0,
                'price_range' => '$$-$$$',
                'facilities' => ['Parkir', 'AC'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.1522,
                'longitude' => 111.8802,
                'is_featured' => false,
            ],
            [
                'name' => 'Raffa Cafe',
                'description' => 'Tempat nongkrong paling oke di kota Bojonegoro. Menyajikan berbagai minuman kekinian dan makanan ringan.',
                'address' => 'Kecamatan Bojonegoro, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'kuliner',
                'image_url' => '',
                'rating' => 4.0,
                'review_count' => 1,
                'price_range' => '$$-$$$',
                'facilities' => ['Parkir', 'WiFi', 'AC', 'Live Music'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.1480,
                'longitude' => 111.8835,
                'is_featured' => false,
            ],
            [
                'name' => 'Tastee Bites Resto',
                'description' => 'Restoran di area Favehotel yang menyajikan masakan Indonesia. Makanan cukup enak dengan suasana hotel yang nyaman.',
                'address' => 'Jl. Jenderal Sudirman, Kecamatan Bojonegoro, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'kuliner',
                'image_url' => '',
                'rating' => 3.5,
                'review_count' => 1,
                'price_range' => '$$-$$$',
                'facilities' => ['Parkir', 'WiFi', 'AC'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.1498,
                'longitude' => 111.8831,
                'is_featured' => false,
            ],
            [
                'name' => 'Bebek Goreng Harissa',
                'description' => 'Restoran spesialis bebek goreng yang lezat di Bojonegoro. Bebek dimasak dengan bumbu khas yang menghasilkan cita rasa gurih dan renyah.',
                'address' => 'Kecamatan Bojonegoro, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'kuliner',
                'image_url' => '',
                'rating' => 4.0,
                'review_count' => 1,
                'price_range' => '$',
                'facilities' => ['Parkir'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.1508,
                'longitude' => 111.8850,
                'is_featured' => false,
            ],
            [
                'name' => 'Javanilla Express',
                'description' => 'Versi express dari Javanilla Resto dengan menu cepat saji Indonesia yang enak dan murah. Cocok untuk makan cepat.',
                'address' => 'Kecamatan Bojonegoro, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'kuliner',
                'image_url' => '',
                'rating' => 4.0,
                'review_count' => 1,
                'price_range' => '$',
                'facilities' => ['Parkir'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.1501,
                'longitude' => 111.8823,
                'is_featured' => false,
            ],
            [
                'name' => 'Kundika Lounge',
                'description' => 'Lounge terbaik di Bojonegoro dengan suasana cozy dan meja biliar. Menyajikan menu Mediterania dan minuman premium.',
                'address' => 'Kecamatan Bojonegoro, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'kuliner',
                'image_url' => '',
                'rating' => 4.4,
                'review_count' => 8,
                'price_range' => '$$$$',
                'facilities' => ['Parkir', 'WiFi', 'AC', 'Meja Biliar', 'Live Music'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.1496,
                'longitude' => 111.8826,
                'is_featured' => false,
            ],
            [
                'name' => 'Singapore Resto & Cafe',
                'description' => 'Resto dan coffee shop yang menyajikan masakan Cina dan makanan laut. Harga standar dengan rasa yang enak.',
                'address' => 'Kecamatan Bojonegoro, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'kuliner',
                'image_url' => '',
                'rating' => 3.8,
                'review_count' => 10,
                'price_range' => '$',
                'facilities' => ['Parkir', 'WiFi', 'AC'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.1504,
                'longitude' => 111.8817,
                'is_featured' => false,
            ],
            [
                'name' => 'Warung Bakso Ora Patek Enak',
                'description' => 'Warung bakso khas Bojonegoro yang terkenal dengan rasanya yang asli enak. Bakso besar dengan kuah kaldu sapi yang gurih.',
                'address' => 'Kecamatan Bojonegoro, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'kuliner',
                'image_url' => '',
                'rating' => 4.0,
                'review_count' => 3,
                'price_range' => '$',
                'facilities' => ['Parkir'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.1515,
                'longitude' => 111.8843,
                'is_featured' => false,
            ],
            [
                'name' => 'Warung GW',
                'description' => 'Warung makan Indonesia dengan menu sederhana dan harga terjangkau. Tempat makan favorit warga lokal Bojonegoro.',
                'address' => 'Kecamatan Bojonegoro, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'kuliner',
                'image_url' => '',
                'rating' => 0,
                'review_count' => 0,
                'price_range' => '$',
                'facilities' => ['Parkir'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.1510,
                'longitude' => 111.8840,
                'is_featured' => false,
            ],
            [
                'name' => 'Bujana Coffee Shop',
                'description' => 'Coffee shop populer dengan rating tinggi di Bojonegoro. Menyajikan kopi berkualitas dan menu Cina dalam suasana modern.',
                'address' => 'Kecamatan Bojonegoro, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'kuliner',
                'image_url' => '',
                'rating' => 4.7,
                'review_count' => 9,
                'price_range' => '$$-$$$',
                'facilities' => ['Parkir', 'WiFi', 'AC', 'Coworking Space'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.1499,
                'longitude' => 111.8829,
                'is_featured' => false,
            ],
            [
                'name' => 'Cinta Cakes & Bakery',
                'description' => 'Toko kue dan bakery dengan berbagai pilihan kue dan roti yang lezat. Rating tinggi untuk kualitas produknya.',
                'address' => 'Kecamatan Bojonegoro, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'kuliner',
                'image_url' => '',
                'rating' => 4.3,
                'review_count' => 3,
                'price_range' => '$$-$$$',
                'facilities' => ['Parkir', 'AC'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.1507,
                'longitude' => 111.8833,
                'is_featured' => false,
            ],
            [
                'name' => 'Warung Sate Gule Pak Tondo',
                'description' => 'Ikon kuliner Bojonegoro yang selalu ramai. Sate kambing dan gule dengan racikan bumbu khas rempah. Dagingnya empuk, kuah gulenya gurih dan kental.',
                'address' => 'Kecamatan Bojonegoro, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'kuliner',
                'image_url' => '',
                'rating' => 4.5,
                'review_count' => 50,
                'price_range' => '$',
                'facilities' => ['Parkir', 'Area Terbuka'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.1503,
                'longitude' => 111.8821,
                'is_featured' => false,
            ],
            [
                'name' => 'Warung Kikil Mbah Su Pacul',
                'description' => 'Warung kikil legendaris di kawasan Pacul. Kikil dimasak empuk dengan kuah bening kekuningan yang gurih. Cita rasa tradisional masakan rumahan khas Jawa Timur.',
                'address' => 'Kawasan Pacul, Kecamatan Bojonegoro, Kabupaten Bojonegoro, Jawa Timur',
                'category' => 'kuliner',
                'image_url' => '',
                'rating' => 4.3,
                'review_count' => 35,
                'price_range' => '$',
                'facilities' => ['Parkir'],
                'phone' => null,
                'website' => null,
                'latitude' => -7.1520,
                'longitude' => 111.8815,
                'is_featured' => false,
            ],

            // =============================================
            // OLEH-OLEH (2 entries)
            // =============================================
            [
                'name' => 'Swarna Kriya Indonesia',
                'description' => 'Pusat oleh-oleh terbesar dan terlengkap di Bojonegoro. Menjual aneka oleh-oleh khas, kerajinan lokal, dan camilan khas. Dilengkapi kafe dan restoran di lantai dua.',
                'address' => 'Jl. Gajah Mada, Kp. Baru, Sukorejo, Kecamatan Bojonegoro, Kabupaten Bojonegoro',
                'category' => 'oleh-oleh',
                'image_url' => '',
                'rating' => 4.4,
                'review_count' => 65,
                'price_range' => 'Rp 10.000 - Rp 200.000',
                'facilities' => ['Parkir', 'AC', 'Kafe', 'Restoran', 'WiFi'],
                'phone' => '0851-8964-2253',
                'website' => null,
                'latitude' => -7.1501,
                'longitude' => 111.8827,
                'is_featured' => true,
            ],
            [
                'name' => 'Pusat Oleh-Oleh Dadi Tresno',
                'description' => 'Tempat favorit berburu ledre, camilan khas Bojonegoro terbuat dari pisang dan kelapa. Menyediakan berbagai oleh-oleh dalam kemasan menarik untuk buah tangan.',
                'address' => 'Jl. MH. Thamrin No.28, Klangon, Kecamatan Bojonegoro, Kabupaten Bojonegoro',
                'category' => 'oleh-oleh',
                'image_url' => '',
                'rating' => 4.2,
                'review_count' => 48,
                'price_range' => 'Rp 5.000 - Rp 100.000',
                'facilities' => ['Parkir', 'AC'],
                'phone' => '0823-3349-0171',
                'website' => null,
                'latitude' => -7.1495,
                'longitude' => 111.8810,
                'is_featured' => false,
            ],
        ];

        foreach ($destinations as $data) {
            Destination::create($data);
        }
    }
}
